### ISSUE TITLE
Cannot pip install this package

### ISSUE THREAD

**Issue by pllim** [bqplot/bqplot-gl#12]
I think `jdaviz` needs this package to work with dev version of `bqplot`. But I cannot install this package with `pip`.

```
2021-11-13T02:53:21.9129512Z   Building wheel for bqplot-gl (pyproject.toml): started
2021-11-13T02:53:21.9130298Z   Building wheel for bqplot-gl (pyproject.toml): finished with status 'error'
2021-11-13T02:53:21.9130874Z   ERROR: Command errored out with exit status 1:
2021-11-13T02:53:21.9132164Z    command: /home/runner/work/jdaviz/jdaviz/.tox/py39-test-devdeps/bin/python /home/runner/work/jdaviz/jdaviz/.tox/py39-test-devdeps/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpd6if5d2d
2021-11-13T02:53:21.9133319Z        cwd: /tmp/pip-req-build-crm9glkh
2021-11-13T02:53:21.9133761Z   Complete output (100 lines):
2021-11-13T02:53:21.9134127Z   running bdist_wheel
2021-11-13T02:53:21.9134460Z   running jsdeps
2021-11-13T02:53:21.9135012Z   Installing build dependencies with npm.  This may take a while...
2021-11-13T02:53:21.9135487Z   > yarn install
2021-11-13T02:53:21.9135792Z   yarn install v1.22.17
2021-11-13T02:53:21.9136159Z   [1/4] Resolving packages...
2021-11-13T02:53:21.9136533Z   [2/4] Fetching packages...
2021-11-13T02:53:21.9136936Z   [3/4] Linking dependencies...
2021-11-13T02:53:21.9137742Z   warning "@jupyter-widgets/base > @lumino/coreutils@1.8.2" has unmet peer dependency "crypto@1.0.1".
2021-11-13T02:53:21.9138603Z   warning "@jupyterlab/builder > @jupyterlab/buildutils > verdaccio > clipanion@3.0.1" has unmet peer dependency "typanion@*".
2021-11-13T02:53:21.9139371Z   warning Workspaces can only be enabled in private projects.
2021-11-13T02:53:21.9139965Z   warning Workspaces can only be enabled in private projects.
2021-11-13T02:53:21.9140451Z   [4/4] Building fresh packages...
2021-11-13T02:53:21.9140802Z   Done in 11.03s.
2021-11-13T02:53:21.9141094Z   > yarn run build:prod
2021-11-13T02:53:21.9141415Z   yarn run v1.22.17
2021-11-13T02:53:21.9141884Z   $ yarn run build:lib && yarn run build:nbextension && yarn run build:labextension
2021-11-13T02:53:21.9142340Z   $ tsc
2021-11-13T02:53:21.9143006Z   src/LinesGLView.ts(61,17): error TS2339: Property 'extras' does not exist on type 'Figure'.
2021-11-13T02:53:21.9143883Z   src/LinesGLView.ts(62,17): error TS2339: Property 'extras' does not exist on type 'Figure'.
2021-11-13T02:53:21.9144738Z   src/LinesGLView.ts(127,17): error TS2339: Property 'extras' does not exist on type 'Figure'.
2021-11-13T02:53:21.9145599Z   src/LinesGLView.ts(131,17): error TS2339: Property 'extras' does not exist on type 'Figure'.
2021-11-13T02:53:21.9146448Z   src/LinesGLView.ts(143,17): error TS2339: Property 'extras' does not exist on type 'Figure'.
2021-11-13T02:53:21.9147306Z   src/LinesGLView.ts(148,17): error TS2339: Property 'extras' does not exist on type 'Figure'.
2021-11-13T02:53:21.9148167Z   src/LinesGLView.ts(185,38): error TS2339: Property 'extras' does not exist on type 'Figure'.
2021-11-13T02:53:21.9149039Z   src/ScatterGLView.ts(319,17): error TS2339: Property 'extras' does not exist on type 'Figure'.
2021-11-13T02:53:21.9149934Z   src/ScatterGLView.ts(320,17): error TS2339: Property 'extras' does not exist on type 'Figure'.
2021-11-13T02:53:21.9150814Z   src/ScatterGLView.ts(560,38): error TS2339: Property 'extras' does not exist on type 'Figure'.
2021-11-13T02:53:21.9151708Z   src/ScatterGLView.ts(573,19): error TS2339: Property 'extras' does not exist on type 'Figure'.
2021-11-13T02:53:21.9152596Z   src/ScatterGLView.ts(612,19): error TS2339: Property 'extras' does not exist on type 'Figure'.
2021-11-13T02:53:21.9153470Z   src/ScatterGLView.ts(620,19): error TS2339: Property 'extras' does not exist on type 'Figure'.
2021-11-13T02:53:21.9154357Z   src/ScatterGLView.ts(747,19): error TS2339: Property 'extras' does not exist on type 'Figure'.
2021-11-13T02:53:21.9155249Z   src/ScatterGLView.ts(769,19): error TS2339: Property 'extras' does not exist on type 'Figure'.
2021-11-13T02:53:21.9156125Z   src/ScatterGLView.ts(802,19): error TS2339: Property 'extras' does not exist on type 'Figure'.
2021-11-13T02:53:21.9157018Z   src/ScatterGLView.ts(816,19): error TS2339: Property 'extras' does not exist on type 'Figure'.
2021-11-13T02:53:21.9158026Z   src/ScatterGLView.ts(830,19): error TS2339: Property 'extras' does not exist on type 'Figure'.
2021-11-13T02:53:21.9158921Z   src/ScatterGLView.ts(844,19): error TS2339: Property 'extras' does not exist on type 'Figure'.
2021-11-13T02:53:21.9160402Z   src/ScatterGLView.ts(859,19): error TS2339: Property 'extras' does not exist on type 'Figure'.
2021-11-13T02:53:21.9161283Z   src/ScatterGLView.ts(901,17): error TS2339: Property 'extras' does not exist on type 'Figure'.
2021-11-13T02:53:21.9162174Z   src/ScatterGLView.ts(916,17): error TS2339: Property 'extras' does not exist on type 'Figure'.
2021-11-13T02:53:21.9163068Z   src/ScatterGLView.ts(921,17): error TS2339: Property 'extras' does not exist on type 'Figure'.
2021-11-13T02:53:21.9164066Z   src/ScatterGLView.ts(962,17): error TS2339: Property 'extras' does not exist on type 'Figure'.
2021-11-13T02:53:21.9165003Z   src/ScatterGLView.ts(966,17): error TS2339: Property 'extras' does not exist on type 'Figure'.
2021-11-13T02:53:21.9165893Z   src/ScatterGLView.ts(1072,21): error TS2339: Property 'extras' does not exist on type 'Figure'.
2021-11-13T02:53:21.9166794Z   src/ScatterGLView.ts(1077,21): error TS2339: Property 'extras' does not exist on type 'Figure'.
2021-11-13T02:53:21.9167687Z   src/ScatterGLView.ts(1082,21): error TS2339: Property 'extras' does not exist on type 'Figure'.
2021-11-13T02:53:21.9168573Z   src/ScatterGLView.ts(1146,23): error TS2339: Property 'extras' does not exist on type 'Figure'.
2021-11-13T02:53:21.9169465Z   src/ScatterGLView.ts(1151,21): error TS2339: Property 'extras' does not exist on type 'Figure'.
2021-11-13T02:53:21.9170370Z   src/utils.ts(59,15): error TS2339: Property 'needsWebGLContext' does not exist on type 'Figure'.
2021-11-13T02:53:21.9171308Z   src/utils.ts(60,12): error TS2339: Property 'needsWebGLContext' does not exist on type 'Figure'.
2021-11-13T02:53:21.9172163Z   src/utils.ts(63,15): error TS2339: Property 'extras' does not exist on type 'Figure'.
2021-11-13T02:53:21.9172942Z   src/utils.ts(64,24): error TS2339: Property 'extras' does not exist on type 'Figure'.
2021-11-13T02:53:21.9173753Z   src/utils.ts(68,14): error TS2339: Property 'webGLCanvas' does not exist on type 'Figure'.
2021-11-13T02:53:21.9174594Z   src/utils.ts(69,14): error TS2339: Property 'webGLContext' does not exist on type 'Figure'.
2021-11-13T02:53:21.9175429Z   src/utils.ts(115,12): error TS2339: Property 'renderHooks' does not exist on type 'Figure'.
2021-11-13T02:53:21.9176278Z   src/utils.ts(118,12): error TS2339: Property 'relayoutHooks' does not exist on type 'Figure'.
2021-11-13T02:53:21.9176836Z   error Command failed with exit code 1.
2021-11-13T02:53:21.9177463Z   info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2021-11-13T02:53:21.9178278Z   error Command failed with exit code 1.
2021-11-13T02:53:21.9178912Z   info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2021-11-13T02:53:21.9179554Z   Traceback (most recent call last):
2021-11-13T02:53:21.9181840Z     File "/home/runner/work/jdaviz/jdaviz/.tox/py39-test-devdeps/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
2021-11-13T02:53:21.9182796Z       main()
2021-11-13T02:53:21.9183910Z     File "/home/runner/work/jdaviz/jdaviz/.tox/py39-test-devdeps/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
2021-11-13T02:53:21.9184906Z       json_out['return_val'] = hook(**hook_input['kwargs'])
2021-11-13T02:53:21.9186157Z     File "/home/runner/work/jdaviz/jdaviz/.tox/py39-test-devdeps/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
2021-11-13T02:53:21.9187069Z       return _build_backend().build_wheel(wheel_directory, config_settings,
2021-11-13T02:53:21.9188142Z     File "/tmp/pip-build-env-jyfyu8p1/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 230, in build_wheel
2021-11-13T02:53:21.9189261Z       return self._build_with_temp_dir(['bdist_wheel'], '.whl',
2021-11-13T02:53:21.9190263Z     File "/tmp/pip-build-env-jyfyu8p1/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
2021-11-13T02:53:21.9190978Z       self.run_setup()
2021-11-13T02:53:21.9191870Z     File "/tmp/pip-build-env-jyfyu8p1/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 158, in run_setup
2021-11-13T02:53:21.9193839Z       exec(compile(code, __file__, 'exec'), locals())
2021-11-13T02:53:21.9194910Z     File "setup.py", line 67, in <module>
2021-11-13T02:53:21.9195433Z       setup(**setup_args)
2021-11-13T02:53:21.9196732Z     File "/tmp/pip-build-env-jyfyu8p1/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 159, in setup
2021-11-13T02:53:21.9198183Z       return distutils.core.setup(**attrs)
2021-11-13T02:53:21.9199332Z     File "/opt/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/distutils/core.py", line 148, in setup
2021-11-13T02:53:21.9200114Z       dist.run_commands()
2021-11-13T02:53:21.9200778Z     File "/opt/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/distutils/dist.py", line 966, in run_commands
2021-11-13T02:53:21.9201386Z       self.run_command(cmd)
2021-11-13T02:53:21.9202359Z     File "/opt/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/distutils/dist.py", line 985, in run_command
2021-11-13T02:53:21.9202904Z       cmd_obj.run()
2021-11-13T02:53:21.9203844Z     File "/tmp/pip-build-env-jyfyu8p1/overlay/lib/python3.9/site-packages/jupyter_packaging/setupbase.py", line 502, in run
2021-11-13T02:53:21.9204598Z       [self.run_command(cmd) for cmd in cmds]
2021-11-13T02:53:21.9205584Z     File "/tmp/pip-build-env-jyfyu8p1/overlay/lib/python3.9/site-packages/jupyter_packaging/setupbase.py", line 502, in <listcomp>
2021-11-13T02:53:21.9206348Z       [self.run_command(cmd) for cmd in cmds]
2021-11-13T02:53:21.9206980Z     File "/opt/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/distutils/cmd.py", line 313, in run_command
2021-11-13T02:53:21.9207656Z       self.distribution.run_command(command)
2021-11-13T02:53:21.9208341Z     File "/opt/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/distutils/dist.py", line 985, in run_command
2021-11-13T02:53:21.9208883Z       cmd_obj.run()
2021-11-13T02:53:21.9210055Z     File "/tmp/pip-build-env-jyfyu8p1/overlay/lib/python3.9/site-packages/jupyter_packaging/setupbase.py", line 274, in run
2021-11-13T02:53:21.9210750Z       c.run()
2021-11-13T02:53:21.9211676Z     File "/tmp/pip-build-env-jyfyu8p1/overlay/lib/python3.9/site-packages/jupyter_packaging/setupbase.py", line 380, in run
2021-11-13T02:53:21.9212785Z       run(npm_cmd + ['run', build_cmd], cwd=node_package)
2021-11-13T02:53:21.9213734Z     File "/tmp/pip-build-env-jyfyu8p1/overlay/lib/python3.9/site-packages/jupyter_packaging/setupbase.py", line 225, in run
2021-11-13T02:53:21.9214538Z       return subprocess.check_call(cmd, **kwargs)
2021-11-13T02:53:21.9215225Z     File "/opt/hostedtoolcache/Python/3.9.8/x64/lib/python3.9/subprocess.py", line 373, in check_call
2021-11-13T02:53:21.9215911Z       raise CalledProcessError(retcode, cmd)
2021-11-13T02:53:21.9216903Z   subprocess.CalledProcessError: Command '['/usr/local/bin/yarn', 'run', 'build:prod']' returned non-zero exit status 1.
```

xref spacetelescope/jdaviz#966

**Comment by pllim** [comment]
A year later, still the same problem, see https://github.com/spacetelescope/jdaviz/pull/1776

**Comment by pllim** [comment]
I think this is still a problem in 2023. In fact, it is worrying because now it pops up in `bqplot==0.13.0a0`. See https://github.com/spacetelescope/jdaviz/actions/runs/5585444163/job/15126165828

**Comment by martinRenou** [comment]
Looks like I forgot to publish bqplot-gl on PyPI and NPM!

**Comment by pllim** [comment]
Pushing the alpha release out to https://pypi.org/project/bqplot-gl/0.1.0a0/ seems to have solved the problem. Thanks!
